Algoritmo "semnome"

Var
OpcaoDoSistema : inteiro
Nome : caractere
Idade : inteiro
Inicio
OpcaoDoSistema := 1
enquanto OpcaoDoSistema = 1 faca
escreval("1 - Cadastra novo usuário")
escreval("2 - Listar todos os usuários cadastrados")
escreval("3 - Sair do sistema")
escreval()
leia(OpcaoDoSistema)
escreval()
se (OpcaoDoSistema = 1) entao
escreva("Nome do Usuário: ")
leia(Nome)
escreva("Idade do Usuário: ")
leia(idade)
escreval()
fimse
fimenquanto

Fimalgoritmo