Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2023
Var
nome: caractere
idade: inteiro
altura: real
texto: caractere
Inicio
nome <- "Marcos"
altura <- 1.80
idade <- 29
Escreval("meu nome é : " , nome)
Escreval("minha altura é : " , altura)
Escreval("minha idade é : " , idade)
Fimalgoritmo